
// Getting Movies
export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";

//Getting search Movie

export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_FAILURE = "SEARCH_MOVIES_FAILURE";

//Get Movie detail

export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS"
export const GET_MOVIE_DETAILS_SUCESS = "GET_MOVIE_DETAILS_SUCESS"
export const GET_MOVIE_DETAILS_FAILURE = "GET_MOVIE_DETAILS_FAILURE"

export const GET_CAST_AND_CREW = "GET_CAST_AND_CREW"
export const GET_MOVIE_REVIEW = "GET_MOVIE_REVIEW"
export const GET_MOVIE_VIDEOS = "GET_MOVIE_VIDEOS"
